# font
font_family    Iosevka
font_size 14

# cursor
cursor_shape beam
cursor_beam_thickness 3
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_stop_blinking_after 15.0
scrollback_lines 10000

url_color #0c0c07
url_style straight
detect_urls yes
open_url_with default

pointer_shape_when_grabbed arrow
enable_audio_bell no

active_border_color #0c2c0c

background_blur 32
background_opacity 0.95

editor nvim
clipboard_max_size 10000
# BEGIN_KITTY_THEME
# Black Metal
# include current-theme.conf
include rose-pine.conf 
# include Black Metal.conf
# END_KITTY_THEME
